### ISSUE TITLE
Target Performance of RedisRaft

### ISSUE THREAD

**Issue by yuyilei** [RedisLabs/redisraft#119]
Hi Redis team, I have a question about target performance of RedisRaft. 
I didn't find any official performance data of RedisRaft. so I deployed a RedisRaft cluster with 3 nodes in Azure to test. Each node has 4 CPUs and 16 GB RAM. Then I used the redis-benmark to test the performace.

Results from a RedisRaft cluster: 
```shell 
$ src/redis-benchmark -h 10.1.0.6 -p 5003 -n 200000 -q
PING_INLINE: 69300.07 requests per second, p50=0.423 msec
PING_MBULK: 71149.05 requests per second, p50=0.415 msec
SET: 246.90 requests per second, p50=188.799 msec
```

Comparing to a normal redis server: 
```shell 
$ src/redis-benchmark -h 10.1.0.7 -p 5004 -n 200000 -q
PING_INLINE: 73340.66 requests per second, p50=0.431 msec
PING_MBULK: 63653.72 requests per second, p50=0.479 msec
SET: 72437.52 requests per second, p50=0.479 msec
```

From the results, the write operations in RedisRaft are very very slow, and the read operations are also than normal redis.  I guess it may caused by RedisRaft's persistence mechanism of strong consistency, so it become bound to disk I/O latency. But I think it's unworhty to avhieve strong consistency by losing so much performance. So I wonder what's the target performace of RedisRaft？ 
And by the way, is there any official benchmark and test result of RedisRaft as a reference?  My test result may be inaccurate for some reasons.

Thanks.

**Comment by yossigo** [comment]
@yuyilei There is no target at this point, and we do have a lot of optimizations that haven't been done yet. It will naturally always be slower than Redis, but there are many things to consider:
* Scaling up using sharding can improve overall TPS
* Client-side pipelining as well as server-side batching and parallelization can improve TPS (but not necessarily latency)

**Comment by yuyilei** [comment]
@yossigo , thanks for your explantion! Let me add something. 

I test my redisRaft again, the results are much quicker than before, which makes more sences. 

RedisRaft cluster: 
```shell
$ src/redis-benchmark -h 10.1.0.4 -p 5001 -n 200000 -q
PING_INLINE: 68728.52 requests per second, p50=0.423 msec
PING_MBULK: 73152.89 requests per second, p50=0.415 msec
SET: 15586.04 requests per second, p50=3.095 msec
GET: 18066.85 requests per second, p50=2.567 msec
INCR: 15395.27 requests per second, p50=3.111 msec
LPUSH: 15644.56 requests per second, p50=3.095 msec
RPUSH: 15452.37 requests per second, p50=3.127 msec
LPOP: 15421.39 requests per second, p50=3.127 msec
RPOP: 15191.80 requests per second, p50=3.143 msec
SADD: 15626.22 requests per second, p50=3.079 msec
HSET: 15045.51 requests per second, p50=3.183 msec
SPOP: 15954.05 requests per second, p50=3.031 msec
ZADD: 15028.55 requests per second, p50=3.215 msec
ZPOPMIN: 15633.55 requests per second, p50=3.079 msec
LPUSH (needed to benchmark LRANGE): 15446.40 requests per second, p50=3.119 msec
LRANGE_100 (first 100 elements): 16366.61 requests per second, p50=2.831 msec
LRANGE_300 (first 300 elements): 12982.80 requests per second, p50=3.447 msec
LRANGE_500 (first 500 elements): 10620.22 requests per second, p50=4.039 msec
LRANGE_600 (first 600 elements): 9959.66 requests per second, p50=4.279 msec
MSET (10 keys): 12648.62 requests per second, p50=3.823 msec
```

Compare to a normal single redis sever, the performance of normal single redis is about five times of redisRaft cluster with 3 nodes.

A normal redis server:
```shell
$ src/redis-benchmark -h 10.1.0.7 -p 5004 -n 200000 -q
PING_INLINE: 72516.32 requests per second, p50=0.439 msec
PING_MBULK: 68728.52 requests per second, p50=0.439 msec
SET: 70972.32 requests per second, p50=0.463 msec
GET: 71377.59 requests per second, p50=0.463 msec
INCR: 73610.60 requests per second, p50=0.431 msec
LPUSH: 71454.09 requests per second, p50=0.439 msec
RPUSH: 69156.30 requests per second, p50=0.511 msec
LPOP: 72966.07 requests per second, p50=0.439 msec
RPOP: 71839.09 requests per second, p50=0.423 msec
SADD: 73610.60 requests per second, p50=0.439 msec
HSET: 70521.86 requests per second, p50=0.463 msec
SPOP: 67226.89 requests per second, p50=0.479 msec
ZADD: 71352.12 requests per second, p50=0.439 msec
ZPOPMIN: 67750.68 requests per second, p50=0.511 msec
LPUSH (needed to benchmark LRANGE): 71890.73 requests per second, p50=0.455 msec
LRANGE_100 (first 100 elements): 41902.37 requests per second, p50=0.687 msec
LRANGE_300 (first 300 elements): 18233.20 requests per second, p50=1.439 msec
LRANGE_500 (first 500 elements): 12461.06 requests per second, p50=2.047 msec
LRANGE_600 (first 600 elements): 10883.76 requests per second, p50=2.327 msec
MSET (10 keys): 69783.67 requests per second, p50=0.479 msec
```

It seems that the performance of RedisRaft is not very stable, there may be a bug inside.  Or the issue may be casued by other reasons? like my improper operations.

**Comment by yossigo** [comment]
@yuyilei From the information you included above it's hard to see performance instability. There are a couple of things I'd be watching:
* Being close to resource limits, you're more likely going to be affected by random spikes.
* Make sure the cluster is stable throughout the benchmark, i.e. no re-election takes place.

**Comment by yuyilei** [comment]
@yossigo, thanks for your reply！

In the earliest test, in which the write operations are very slow, re-election did happened in redisraft cluster. But in fact the re-election is a normal action is raft cluster, why it could degrade the performance of write operations in redisraft cluster?

And here is another thing to watch out for. In a test in  23 July, at first write operations like SET, INCR are very slow, until LPOP, it came to 10k and after this test, the results of subsequent tests all could reach 10k, regardless of using client pipeline. 
It's weird that the performance of write operations in one test are so different. So I'm inclined to think the performace of redisraft is instable because of some bugs in it.

![image](https://user-images.githubusercontent.com/22349304/126941874-e0364a74-8544-47c6-a5ae-1a6408b184a8.png)

**Comment by fadidahanna** [comment]
In the past 2y we improved our performance, we invite you to rerun your tests and see if these issues are still relevant.
