### ISSUE TITLE
Using RedisModule_GetDetachedThreadSafeContext to set the module thread safe context

### ISSUE THREAD

**Issue by dipAch** [RedisLabs/redisraft#121]
Currently when initializing the RedisRaft module in `raft.c::RedisRaftInit`, we are assigning the thread-safe `RedisModuleCtx` to the global raft context - `RedisRaftCtx`.

```
RRStatus RedisRaftInit(RedisModuleCtx *ctx, RedisRaftCtx *rr, RedisRaftConfig *config)
{
    ...
    ...

    rr->ctx = RedisModule_GetThreadSafeContext(NULL);

    ...
    ...
    ...

    return RR_OK;
}
```

To fetch the thread safe module context, we are currently using the **RedisModule_GetThreadSafeContext** API.

But, since we are  not passing any `RedisModuleBlockedClient` parameter to the API call, the returned thread safe module context ptr is detached from any blocked client. So, will there be any side-effects of using **RedisModule_GetDetachedThreadSafeContext** instead?

The Modules API documentation suggests using the detached thread safe context API call, if we are not bound to a blocked client.

**Comment by yossigo** [comment]
@dipAch You are right, it was created before `RedisModule_GetDetachedThreadSafeContext` existed. Practically it doesn't make a real difference at the moment though, but it would be cleaner to correct that.

**Comment by dipAch** [comment]
Thanks @yossigo. I'll raise a patch to update the same and link here.
