### ISSUE TITLE
Premature node promotion may affect cluster availability

### ISSUE THREAD

**Issue by tezc** [RedisLabs/redisraft#125]
Related algorithm described in dissertation (Chapter 4) :
 - New node is added as NON-VOTING.
 - New node receives entries.
 - Leader decides new node has caught up and can be promoted to VOTING. 

To decide when to promote, an algorithm is suggested in section 4.2.1. Normally, I'd expect this to be handled by a raft library but it is exposed outside here : 

https://github.com/RedisLabs/redisraft/blob/e84389ec0191d4bfc6941e6b5c9e140e8265a68f/raft.c#L493

Algorithm described in the paper should be implemented here or directly in the library.

**Comment by yossigo** [comment]
The impact of this issue is potential availability issue. For example, in a three node cluster:

* New node 4 joins and gets promoted before it's up to date
* An existing follower node becomes unavailable
* The cluster will be unable to commit (quorum = 3) until the new node is fully up to date

**Comment by tezc** [comment]
https://github.com/RedisLabs/redisraft/blob/27b03f072bee0a3e8b0746a842593594d1f2af2d/deps/raft/src/raft_server.c#L725

This line assumes follower will reach same log index with the leader. This will never be true if the leader is receiving new entries frequently. On a write-heavy system, nodes cannot become voter due to this check.

**Comment by fadidahanna** [comment]
Irrelevant anymore, since right now we never promote a node prematurely, we promote a node only when it has all entries.
