### ISSUE TITLE
Node state should be either voting or non-voting

### ISSUE THREAD

**Issue by tezc** [RedisLabs/redisraft#126]
Only VOTING and NON-VOTING states are required for a node. e.g removing a node from the cluster, setting it active or non active is not actually required. 

An example configuration struct :

```c
struct conf_node {
    uint64_t node_id;
    uint8_t state;             // voter or non-voter
    char *addr;
}

struct conf {
     uint64_t index;           // Entry index of this configuration
     struct conf_node *nodes;  // Cluster nodes
     int node_count;                  
     struct conf *prev;        //Previous configuration if any. This will point to a configuration instance when a config change entry is appended. It will be destroyed and point to null when that entry is committed.
}
```

pseudo algorithm :

**on_start() :** Create nodes/connections from conf struct instance.
**on_conf_change_append() :** Store current implementation in "conf->prev", apply config change to the conf instance
**on_commit()** : Remove conf->prev
**on_rollback_to(int index);** Check if rollback index is less than "conf->index". If so, rollback to the previous config and re-create nodes/connections from it.

**Comment by yossigo** [comment]
This is really a Raft library issue.
