### ISSUE TITLE
RM_OnLoad logging context

### ISSUE THREAD

**Issue by dipAch** [RedisLabs/redisraft#141]
Hello,

When loading the **redisraft** module via **RedisModule_OnLoad**, currently we are creating a logging context that has the following decision block:

```
    /* Create a logging context */
    if (RedisModule_GetDetachedThreadSafeContext) {
        redis_raft_log_ctx = RedisModule_GetDetachedThreadSafeContext(ctx);
    } else {
        redis_raft_log_ctx = RedisModule_GetThreadSafeContext(NULL);
    }
```

My question is, do we still need the `else` block here to get a detached thread-safe context? Is there some incompatibility between the supported **RedisModule** API versions that **redisraft** uses?

Is it not safe to directly have the **RedisModule_GetDetachedThreadSafeContext** API call for the logging context instantiation?

Regards.

**Comment by yossigo** [comment]
@dipAch You are right, fixing that - thanks.

**Comment by dipAch** [comment]
Sure @yossigo
