### ISSUE TITLE
Error handling improvements

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#180]
Decide on principle, global approach to error handling.
Review different code paths and identify errors that are not handled or not handled well.

Non-exhaustive list:
- [ ] Implement a hook to deal with Raft library assertions at the RedisRaft/Redis level.
- [x] Filesystem issues: write errors, out of disk space, etc.
- [x] All error codes returned from the Raft library are handled properly.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-317
