### ISSUE TITLE
Deterministic Lua Script Execution

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#191]
RedisRaft handles Lua scripts by propagating them through the log, and thus requires them to be deterministic in the same way [Redis Script Replication](https://redis.io/commands/eval#scripts-with-deterministic-writes) works.

Redis 7 moves away from script replication and thus RedisRaft will need to implement a similar mechanism:

* Extend the command filter mechanism to also handle Lua script commands (may require API enhancements to identify the context)
* Reject random commands
* Sort the output of `to-sort` flagged commands
* Potentially interact with the new command introspection mechanism (redis/redis#9656) to handle the above automatically using command flags.

**Comment by yossigo** [comment]
@sjpotter Anything left to do here?

**Comment by sjpotter** [comment]
Implemented by https://github.com/RedisLabs/redisraft/pull/195
