### ISSUE TITLE
Add support for node address change

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#196]
Currently, a node is assigned a hostname / IP address when it joins the cluster, and this address does not change for the entire lifetime of the node.

This is not compatible with some environments where a node can retain its state but may be provisioned with a new IP address or hostname.

We need a mechanism that allows committing a new configuration with a new hostname or IP address for a specific node.

NOTE: There is another special case where a majority of the cluster goes down and get a new address. The above mechanism won't work in this case because there's no quorum to commit a config change, and it requires a different mechanism/workaround for overriding the configuration of individual nodes while they're down.

**Comment by yossigo** [comment]
cc @yaeltzirulnikov

**Comment by tezc** [comment]
@fadidahanna This might be a good start. This is the function that receives node add/remove requests: https://github.com/RedisLabs/redisraft/blob/1425caceca663789ade2f0f1d3ceb1393c522369/src/redisraft.c#L74

I guess we can add `RAFT.NODE UPDATE id addr:port` command just to support address change.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-316
