### ISSUE TITLE
Handle maxmemory enforcement

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#216]
Come up with a good scheme to handle enforcement of `maxmemory`.

We may assume for now that the user is responsible to propagate this configuration to all cluster nodes, as this is also a common pattern with replicas or Redis Cluster nodes.

We need to meet at least the following guarnatees:
* Leader is able to enforce `maxmemory` before appending entries the Raft log.
* Applied commands never spontaneously fail with `-OOM`, as this can lead to an inconsistent dataset. If that still happens, we need to consider that a non-reocverable runtime error and abort the instance.

DoD: 
 - [x] #452 
 - [x] #453 
 - [x] #454

**Comment by fadidahanna** [comment]
https://docs.google.com/document/d/1VdQtt83lWWplVrcaZH9kkqxuITKYz8iYU5bjlnKPh6I/edit#
