### ISSUE TITLE
Allow setting cluster's slot-range at runtime instead of command line

### ISSUE THREAD

**Issue by sjpotter** [RedisLabs/redisraft#223]
Requested via slack: to be able to have a plain command line and configure the cluster's slot range at runtime, such as via a raft.config set slot-range command

**Comment by sjpotter** [comment]
I don't think this can be done via a raft.config set command, as its something that has to be persisted, and config changes aren't persisted.  If a config change has to remain constant between runs of RedisRaft, it has to be set on the command line or not be a config option.

For this, we might be able to leverage the raft.shardgroup replace command to set the slot range after the initial node is created, but this will be part of the resharding discussion.

**Comment by yossigo** [comment]
@sjpotter Right now it's an immutable config and kind of a hack. We could probably allow setting it on a node that was started and did not join a cluster yet, but then we'll have a problem on the first restart.

Eventually this will not be immutable config, and we'll need to persist and propagate it, so the above should probably work fine. But until then, what's the use case for handling that? Why would a config command be any easier than passing an argument to the module?

**Comment by sjpotter** [comment]
flotilla seems to want to have all the pods in the cluster of clusters to have a common command line and be configured at runtime

**Comment by yossigo** [comment]
Fixed by #226
