### ISSUE TITLE
Exporting monitoring metrics 

### ISSUE THREAD

**Issue by danni-m** [RedisLabs/redisraft#224]
As a operator, I would want to get advanced metrics to figure out the state of the Raft cluster and to be able to diagnose issues.

**Comment by yossigo** [comment]
@sjpotter @danni-m I suggest to use this issue to put together an initial list of metrics that seem to be useful.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-13
