### ISSUE TITLE
Allow setting node's id at runtime instead of command line

### ISSUE THREAD

**Issue by sjpotter** [RedisLabs/redisraft#225]
Requested via slack: to be able to have a plain command line and configure the node's id at runtime, such as via a raft.config set id command

**Comment by sjpotter** [comment]
I don't see how this can be done as such, my only thought would be that it can be an environment variable that will be read in at startup.  This value has to be consistent from run to run, and hence cannot be set manually at runtime.

**Comment by yossigo** [comment]
@sjpotter Why would an environment variable be any different than an argument passed to the module at load time?

IIRC, we have to consider main scenarios:
1. Node starting before it's part of a cluster. If ID is explicitly configured, it will request this ID from the leader upon joining. If ID is not explicitly configured, it will be received from the leader upon joining.
2. Node starting with snapshot/log already present. If ID is explicitly configured, we validate it matches the files. If not, we just load it.

Is that correct?
If so, would it make sense to say that we support config set for the ID only as long as we're not yet part of the cluster and no other ID was previously set? In all other cases the ID is anyway immutable.

**Comment by sjpotter** [comment]
going backwards

1) the reason for me saying env variable vs cmd line arg, is more related to kubernetes being able somehow able to use the stateful's index as the node id.

however, that seems to not be necessary.  can do sh magic to extract it on the cmd line passed to each pod.

https://stackoverflow.com/questions/56284836/is-there-any-less-hacky-way-of-passing-an-ordinal-index-to-statefulset-environme

2) I was confused that #2 was actually 2 cases

1) node starting when snapshot already present (id stored in snapshot)
2) node starting without snapshot, only log.

for some reason I was thinking node id was only stored in snapshot, not log.  In digging again into the code, I see that it is stored in the log, so should work fine to be a runtime config.

though re https://github.com/RedisLabs/redisraft/issues/223 that would still be an issue.  The solution there would be to control slot range via a shardgroup replace command (right now its ignored for the local cluster, for the shardgroup id that corresponds to it, it just uses the information for the remote clusters)
