### ISSUE TITLE
Need way to migrate keys from one raft cluster to another

### ISSUE THREAD

**Issue by jhershberg** [RedisLabs/redisraft#234]
Should provide similar semantics to the regular Redis cluster migrate command.
Related to #78

**Comment by tezc** [comment]
So, maybe we can bring the discussion here. Combining with @sjpotter 's idea, I suggest two things :

- Source cluster leader will process migrate operations from the current term only. If the term changes, migrate fails.
- Source cluster leader will attach the current term with the key while sending it to the target cluster. The target cluster will reject the key if the term is less than it has ever seen from the source cluster.  

Overall, the steps are : 

1- Migrate command will be sent to source cluster, it'll be written to the raft log.
   - On apply:
       - We'll add the key to a migration map in the state machine. From now on, requests for this key will be replied with TRYAGAIN. The leader will get the dump of the key and associate it with the term and try to send it to the target cluster. Sending is an async operation, not blocking. Migrate command "timeout" can be used here to give up on migration etc.
   - Leader tries to send the key, finally, the result will be written to the log. Whether it was successful or not, when the result entry is applied, the key will be removed from the migration map. After a successful migration, the source cluster can redirect operations to the target cluster. 

2- When the target cluster receives a key from the source cluster, it will check the term and verify it's not less than it has ever seen from this cluster. Consider this scenario :
- Node A is the leader, applied "migrate command" to its state and now it will try to move the key to the target. Meanwhile, another leader is elected, moved the key, completed the operation. Clients started to use the key as it has been migrated successfully. Node A is unaware of that and will try to move the older version of the key. Term check should prevent this. 

3- On each term start, whether the node is the leader or follower, it will clear the migration map and return failure to the client (If the client is connected to that node).

**Comment by fadidahanna** [comment]
https://gist.github.com/sjpotter/e7a4a31dbcab677dfd54b8050cb31f54
Design Doc: https://docs.google.com/document/d/15Au_Ku18tn_CXbMJawesOf_Qye_1EFEDIcknLVLCTdA/edit#heading=h.yluwclwub96n
