### ISSUE TITLE
Fix build on FreeBSD

### ISSUE THREAD

**Issue by tezc** [RedisLabs/redisraft#241]
Fix build on FreeBSD and add it to daily CI

**Comment by yossigo** [comment]
@tezc +1 for fixing known issues with FreeBSD, not sure if adding it to CI will justify the extra noise it may produce.

**Comment by tezc** [comment]
Extra noise because it's FreeBSD or hacky VM on MacOS thing? I was thinking using CirrusCI (Used that without much problems before), thinking again I'm not that sure though (Not sure if we can use it). Daily or weekly or even monthly run of FreeBSD would be nice just to detect platform differences like `getaddrinfo()` returns positive if it fails on some systems and `if (getaddrinfo() < 0) { /* Fail */} ` wouldn't work.

**Comment by yossigo** [comment]
@tezc Both because it's FreeBSD and because of GitHub actions. We could create better CI to handle that, but I think at this point in time the value of FreeBSD support is probably very low and not worth an on-going commitment (beyond sporadic fixes).
