### ISSUE TITLE
Add WATCH support

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#312]

**Comment by fadidahanna** [comment]
Design Doc: https://docs.google.com/document/d/1SMCMsCzhV02yu3iW5-upAPgOYudRsWQdZj4VCSoXL4Q/edit#heading=h.5q538nawhw9w

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-3
