### ISSUE TITLE
Potential issues with connection management

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#315]
Potential issues found while reviewing the authentication support PR.

**Comment by yossigo** [comment]
Update: Not sure if this is still a problem. We noticed some potential issues with unhappy paths after applying changes due to authentication on connection setup.

**Comment by fadidahanna** [comment]
@sjpotter, can you follow up with @yossigo to figure out exactly what is needed here 🙏 

https://github.com/RedisLabs/redisraft/pull/247
