### ISSUE TITLE
Improve proxy connection management

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#35]
Currently nodes use the same connection to exchange Raft related messages (AppendEntries, RequestVote, etc.) and handle follower proxy traffic (i.e. RAFT.ENTRY commands).

Ideally we may want to maintain separate connections for this purpose, and possible use connection pools to improve proxy performance.

Note: we'll need to consider consistency when pushing client requests though to avoid re-ordering and introducing consistency issues.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-127

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-319
