### ISSUE TITLE
Improve RAFT prefix mechanism

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#367]
Right now, `RAFT` is prefixed to all intercepted commands.
It is defined as a write command which is wrong from the Redis perspective.

Proposal:
* Introduce additional `RAFT` variants (e.g. read-only, unsupported command, etc.)
* Allows read/write to be reflected correctly to Redis
* Optimization: saves the need to lookup the command twice (1st in filter, 2nd in module command)

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-127
