### ISSUE TITLE
Consider adding Valgrind build

### ISSUE THREAD

**Issue by tezc** [RedisLabs/redisraft#386]
RedisRaft already has address sanitizer build but there is one case that address sanitizer doesn't catch: Use of uninitialized memory. 

**Solution-1**: Memory sanitizer

There is "memory sanitizer" for this case but GCC does not support it. Clang supports it but we need to add memory sanitizer to Redis first. So, to use this sanitizer, we need to cleanup Redis code base from memory sanitizer issues and then, add it to the RedisRaft. Also, memory sanitizer future is not clear whether it'll exist in future.

**Solution-2**: Valgrind

Probably, it is easier to add Valgrind to RedisRaft. We can already run test suite with valgrind by passing `--valgrind` config to the pytest but we need to surpress some errors and catch failures that we want. Downside is it will cause stability issues as valgrind slows down the execution a lot, we might see lots of test failures.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-295
