### ISSUE TITLE
Sharding and slot_config configurations should be part of CLUSTER INIT command

### ISSUE THREAD

**Issue by tezc** [RedisLabs/redisraft#408]
Currently, `sharding` and `slot_config` config parameters are only used when we initialize the cluster. They should not be node configuration parameters. We should pass them to `CLUSTER INIT` command as arguments. So, these parameters will be part of cluster configuration.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-33
