### ISSUE TITLE
Improve performance for SCAN cmd

### ISSUE THREAD

**Issue by fadidahanna** [RedisLabs/redisraft#432]
`SCAN` is a blocking command, maybe we can split `SCAN` into chunks.

**Comment by tezc** [comment]
Actually, @sjpotter  did it already in the key migration PR. Client is supposed to call `raft.scan` multiple times and batch key names. 

Still, we need to check a few things:

- Figure out the optimum "scan-size" configuration to prevent blocking Redis more than we can afford. 
- Do some benchmarking with multi-az setup. Sending multiple scans to batch key names might become bottleneck of the whole migration performance. 
- Consider moving batching into RedisRaft. There was discussion around moving more migration steps to RedisRaft. Admin can just issue "migrate slot key-count" command and RedisRaft can handle all the batching and migration. In this case, RedisRaft might be able to decide on optimum size.

**Comment by sjpotter** [comment]
raft.scan is similiar to normal redis scan.

returns a 2 element array

a cursor (to be used for next scan call) and an array of key elements (which unlike normal redis scan are 2 element arrays that have the keyname and the slot the key belongs to).

why would multi az will make much of a difference beyond other RO commands?

**Comment by tezc** [comment]
If admin and leader node is not on the same AZ, round-trip latency is ~1 ms. Now, depending on your scan size, batching key names might become slowest part of the migration operation as you need to go to the leader node many times.

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-29
