### ISSUE TITLE
possible crash in raft.snapshot

### ISSUE THREAD

**Issue by sjpotter** [RedisLabs/redisraft#449]
@danni-m saw a crash in what appears to be a RAFT.SNAPSHOT command, but it seems weird situation that I don't know how to diagnose.

[raft_crash-10-07-22.log](https://github.com/RedisLabs/redisraft/files/9084022/raft_crash-10-07-22.log)

**Comment by tezc** [comment]
I think leader sends another message while we are loading the snapshot. 

1- Leader sends the last snapshot chunk and we call `raft_recv_snapshot()` -> `rdbLoad()`. Redis starts loading the data.
2- Leader sends another message.
3- As we didn't block the leader on step 1, Redis tries to process new message while loading rdb file and hits that assert. 

Probably this is not an explored path for Redis as`rdbLoad()` is not part of the module API.

After verifying this is the case, I think we can call `RM_BlockClient()` around `raft_recv_snapshot()` to prevent processing messages while loading the rdb.
