### ISSUE TITLE
RR crashing on restart

### ISSUE THREAD

**Issue by jhershberg** [RedisLabs/redisraft#487]
I have a version of our cluster running for the past 30 days in GKE. Had not looked at it for a while and when I went in just now all the nodes were dead due to RR crashing on:
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 31 Aug 2022 10:18:25.604 # === ASSERTION FAILED ===
1:M 31 Aug 2022 10:18:25.604 # ==> /redisraft/src/cluster.c:662 'sg != NULL' is not true

------ STACK TRACE ------

Backtrace:
/redisraft.so(ShardingInfoRDBLoad+0x127)[0x7f5423ae0397]
/redisraft.so(+0x28905)[0x7f5423af3905]
redis-server *:6379(rdbLoadRioWithLoadingCtx+0x961)[0x48b421]
redis-server *:6379(rdbLoad+0xa6)[0x48bc36]
redis-server *:6379(loadDataFromDisk+0x92)[0x45eb92]
redis-server *:6379(main+0x264)[0x44a3c4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea)[0x7f5423b46d0a]
redis-server *:6379(_start+0x2a)[0x44a92a]

**Comment by tezc** [comment]
[log.zip](https://github.com/RedisLabs/redisraft/files/9462266/log.zip)

I think an older RedisRaft version created that RDB file. So, the RDB file and current RedisRaft do not match. 

With this commit, we changed how we save sharding info into RDB: https://github.com/RedisLabs/redisraft/pull/426.
RDB file has data in the old format somehow.
