### ISSUE TITLE
Is it possible that the redisraft can work with other redis modules?

### ISSUE THREAD

**Issue by jovany-wang** [RedisLabs/redisraft#62]
I have another Redis module which  extends my business from Redis by using Redis module.

Is it possible that I can load 2 modules together, like:

`redis-server --load redisraft   x-module`

-----
It seems we can't. Because the 2 modules have their own commands. emmm, what's the best practice to combine redisraft to my buiness module?

**Comment by yossigo** [comment]
@jovany-wang It really depends on the module. A module that implements simple additional commands/data types can theoretically supported (perhaps it may even work already, didn't check). Anything more complex (e.g. using client blocking) will require more specific work.

It's an interesting discussion - please feel free to share more information about what your other module does or some examples of how this fails.

**Comment by jovany-wang** [comment]
@yossigo 

I have the module which extends Redis by adding the structured relationship table concept on Redis, like SQL-like command:
```
// Create a table named `table_a` with the given schema. (primary indicates the field is a primary key.)
CREATE TABLE `table_a` with schema (id:int:primary, name: str, age: int, score: int);
// Create an index for the score field.
CREATE INDEX FOR `table_a.score`;
```
And then add the records to the table:
```
// Insert the records to table_a.
ADD (0, Allen, 20, 93) to `table_a`;
ADD (1, Jovany, 21, 89) to `table_a`;
ADD (2, Wang, 2, 92) to `table_a`;
```
And then our module will process these commands, and transform these commands to Redis operators.
After adding them, there are some k-v pairs in Redis:
```
       key                                                value
TABLE_table_a_0                                  set{0, Allen, 20, 93}
TABLE_table_a_1                                   set{1, Jovany, 21, 89}
TABLE_table_a_2                                  set{2, Wang, 2,  92}
TABLE_table_a_INDEX_score                    hashset{(93, 0), (89, 1), (92, 2)}
```

So, if we want to query from this table, the thing will get more easy:
```
QUERY (*) FROM table_a WHERE score == 92;
```
This query command will get the id of `table_a` from `TABLE_table_a_INDEX_score` since score is an index of this table.
After that, we get `TABLE_table_a_2` from Redis directly.

That's almost what we do in our module. Summarized that in some words: we extends some commands about table concept by using the Redis operators in our custom's commands.

Since RedisRAFT has come out, I'm considering that it is possible to introduce the redisRAFT and integrate it to my module. Then I can abandon the original code that do more logical to make my Redis instance with a strong consistency.

If I didn't describe it clearly, feel free to point it out.

**Comment by yossigo** [comment]
@jovany-wang The way you describe it, it's likely that such a module can be compatible with Redis Raft. I will have a look at module compatibility and report back if I see any issues or provide more info on how you can try that yourself.

**Comment by jovany-wang** [comment]
@yossigo That sounds great.

**Comment by yossigo** [comment]
@jovany-wang I can confirm simple modules work as expected.
Basically all you need is to load the module on all Raft cluster nodes. You can use the `run.sh` script in the repo as a starting point, add the necessary `--loadmodule` arguments to get your module loaded and test a local 3-node cluster.
