### ISSUE TITLE
Refresh configuration interface

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#65]
The current configuration interface requires a refresh, and we need to do that as early as possible before approaching beta or GA releases.

Things to do:

- [x] Move from an `argument=value` to an `ARGUMENT <value>` format which is a bit easier/more intuitive and similar the the approach taken by other modules.
- [ ] Reconsider and improve names where applicable (and don't forget to update documentation).

**Comment by gavrie** [comment]
As mentioned in #73, we'll define constants for the static strings defined in `config.c` as part of this issue.
