### ISSUE TITLE
Add backtrace support

### ISSUE THREAD

**Issue by gavrie** [RedisLabs/redisraft#66]
When an error value is returned (e.g. `RAFT_ERR_SHUTDOWN`) it’s hard to know where exactly it came from. Some places (especially in the libraft code) log an explicit message before returning the error, but not all of them.

We should add backtrace support (like Redis itself has) to make it easier to debug failures.

**Comment by sjpotter** [comment]
the issue with this is that not all RAFT_ERR_SHUTDOWNS are actually errors.  (i.e. they are expected runtime behavior telling a node to shutdown)

**Comment by yossigo** [comment]
Seems this is not necessary beyond simple logging of the library's context.
