### ISSUE TITLE
Can you add support for getting cluster node information

### ISSUE THREAD

**Issue by Wlitsoft** [RedisLabs/redisraft#71]

**Comment by yossigo** [comment]
@Wlitsoft I'm afraid I'm not sure what you mean by that. There is already a `RAFT.INFO `command that provides information about nodes, is that what you refer to?

**Comment by Wlitsoft** [comment]
> @Wlitsoft I'm afraid I'm not sure what you mean by that. There is already a `RAFT.INFO `command that provides information about nodes, is that what you refer to?

Yes, `RAFT.INFO` can meet my current needs. It's best if there are `cluster nodes` like Redis cluster

**Comment by yossigo** [comment]
@Wlitsoft There is work in progress towards leveraging the Redis Cluster protocol to allow easier integration with cluster compatible clients, which will include `CLUSTER NODES` and `CLUSTER SLOTS`. Thanks for raising this.
