### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#77]
Perform a round of benchmark and profiling to come up with a performance improvement plan.
Some issues are already known, see #76 and #35

**Comment by fadidahanna** [comment]
The latest knows performance numbers can be found in this PR: https://github.com/RedisLabs/redisraft/pull/192

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-12
