### ISSUE TITLE
Resharding support

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#78]
The initial sharding support (#73) provides the basic functionality but does not offer a way to handle re-sharding and migration of keys between shardsgroups. Initially, this will require substantial design.

Subtasks: 
- [x] #430 
- [x] #431 
- [x] #432 
- [x] #433

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-14
