### ISSUE TITLE
Is it necessary to check `RedisModule_RegisterCommandFilter` in `setRaftizeMode`?

### ISSUE THREAD

**Issue by MichaelScofield** [RedisLabs/redisraft#84]
... since it's already checked in `redisraft.c`:

```c
    /* Sanity check Redis version */
    if (RedisModule_SubscribeToServerEvent == NULL ||
            RedisModule_RegisterCommandFilter == NULL) {
        RedisModule_Log(ctx, REDIS_NOTICE, "Redis Raft requires Redis 6.0 or newer!");
        return REDISMODULE_ERR;
    }
```

that is before call to `setRaftizeMode`:

```c
RRStatus setRaftizeMode(RedisRaftCtx *rr, RedisModuleCtx *ctx, bool flag)
{
    /* Is it supported by Redis? */
    if (!RedisModule_RegisterCommandFilter) {
        /* No; but if flag is false no harm is done. */
        return flag ? RR_ERROR : RR_OK;
    }
```

So the `if (!RedisModule_RegisterCommandFilter)` is always false, and the `bool raftize_all_commands` in `RedisRaftConfig` is not actually used.

**Comment by yossigo** [comment]
@MichaelScofield You are right, this is redundant. In fact the entire raftize concept should be revamped and become the only mode of operation, requiring Redis 6.x or better.
